ALTER TABLE "tryouts" ALTER COLUMN "hostId" DROP NOT NULL;
ALTER TABLE "tryouts" ALTER COLUMN "hostDiscordId" DROP NOT NULL;
ALTER TABLE "tryouts" ADD COLUMN IF NOT EXISTS "automated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "tryouts" ADD COLUMN IF NOT EXISTS "hostKind" TEXT NOT NULL DEFAULT 'human';
