ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "notifyAsked"   BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "notifyEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "notifyPrefs"   JSONB;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "lastRoleCheck" TIMESTAMP(3);
