#!/usr/bin/env node
// scripts/build-emoji.js
// Rasterises the MET emoji set (scripts/emoji/manifest.js) into
// client/public/img/emoji/<name>.png.
//
//   node scripts/build-emoji.js
//
// The PNGs are COMMITTED, so you only need to run this after editing the
// manifest — the app and the Discord syncer both read the built files.
//
// Discord wants a raster image under 256 KB and renders emoji at ~22px, so we
// render at 128×128 on a transparent background. There's no ImageMagick or
// Pillow in this project, so the rasteriser is headless Chromium via Playwright
// — a devDependency, and only needed for this script.

const fs   = require('fs');
const path = require('path');
const { EMOJI } = require('./emoji/manifest');

const OUT = path.join(__dirname, '../client/public/img/emoji');
const SIZE = 128;

function svgFor(def) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="${SIZE}" height="${SIZE}">${def.svg}</svg>`;
}

async function main() {
  fs.mkdirSync(OUT, { recursive: true });

  // Always write the SVG sources — they're the reviewable artwork, and they let
  // the set be re-rasterised anywhere without this script.
  const svgDir = path.join(OUT, 'svg');
  fs.mkdirSync(svgDir, { recursive: true });
  for (const def of EMOJI) fs.writeFileSync(path.join(svgDir, def.name + '.svg'), svgFor(def));
  console.log(`Wrote ${EMOJI.length} SVG source(s) to ${path.relative(process.cwd(), svgDir)}`);

  // The browser-side fallback map. client/public/js/emoji.js needs to know the
  // unicode character behind each name so a missing PNG still renders as
  // something — generating it here keeps the manifest the only source of truth.
  const map = {};
  for (const def of EMOJI) map[def.name] = def.fallback;
  const mapFile = path.join(__dirname, '../client/public/js/emoji-map.js');
  fs.writeFileSync(mapFile,
    '// GENERATED by scripts/build-emoji.js from scripts/emoji/manifest.js — do not edit.\n'
    + 'window.MET_EMOJI_FALLBACK = ' + JSON.stringify(map, null, 2) + ';\n');
  console.log(`Wrote ${path.relative(process.cwd(), mapFile)}`);

  let chromium;
  try {
    ({ chromium } = require('playwright'));
  } catch (e) {
    console.error('\nplaywright is not installed, so the PNGs were not rendered.');
    console.error('  npm i -D playwright && npx playwright install chromium');
    console.error('The SVG sources above are still up to date.');
    process.exit(1);
  }

  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: SIZE, height: SIZE }, deviceScaleFactor: 1 });

  let built = 0;
  for (const def of EMOJI) {
    // A bare SVG document, no margins — the screenshot IS the emoji.
    await page.setContent(
      `<style>html,body{margin:0;padding:0;background:transparent;}svg{display:block;}</style>${svgFor(def)}`,
      { waitUntil: 'load' },
    );
    const file = path.join(OUT, def.name + '.png');
    await page.screenshot({ path: file, omitBackground: true });
    const kb = (fs.statSync(file).size / 1024).toFixed(1);
    if (fs.statSync(file).size > 256 * 1024) console.warn(`  ! ${def.name} is ${kb} KB — over Discord's 256 KB limit`);
    built++;
  }
  await browser.close();

  const forDiscord = EMOJI.filter(e => e.discord !== false).length;
  console.log(`Built ${built} PNG(s) in ${path.relative(process.cwd(), OUT)}`);
  console.log(`${forDiscord} are uploaded to Discord; ${built - forDiscord} are site-only.`);
}

main().catch(e => { console.error(e); process.exit(1); });
